import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Header} from "../components/Header";
import {Dialog} from "../components/Dialog";


const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Чат</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Header/>
                <input className={styles.search} type="text" placeholder="Найти пользователя..."/>
                <div className={styles.dialogs}>
                    <Dialog/>
                    <Dialog/>
                    <Dialog/>
                </div>
            </main>
        </div>
    )
}

export default Home
