import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from "next/image";

const myLoader=()=>{
    return "https://st.depositphotos.com/1008939/3281/i/600/depositphotos_32817757-stock-photo-smiling-man.jpg";
}

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Чат</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <header className={styles.header}>
                    <div className={styles.logo}>
                        <Image
                            loader={myLoader}
                            src={"https://st.depositphotos.com/1008939/3281/i/600/depositphotos_32817757-stock-photo-smiling-man.jpg"}
                            alt={"В"}
                            width={45}
                            height={45}/>
                    </div>
                    <h1 className={styles.title}>Чат</h1>
                </header>
                <input className={styles.search} type="text" placeholder="Найти пользователя..."/>
                <div className={styles.dialogs}></div>
            </main>
        </div>
    )
}

export default Home
